language: elixir
sudo: false
script: mix test
matrix:
  include:
  - elixir: '1.9.4'
    otp_release: '22.2'
  - elixir: '1.9.0'
    otp_release: '22.0'
  - elixir: '1.8.2'
    otp_release: '21.3'
  - elixir: '1.7.3'
    otp_release: '21.1'
  - elixir: '1.6.6'
    otp_release: '21.0'
